name: ci

on:
  pull_request:
    branch: ["main"]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run Go Tests
        run: go test ./...
